version: "3.8"

services:
  client:
    build:
      context: ./my-blog-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./my-blog-app:/app
      - /app/node_modules
    

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/my-blog-db
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - FACEBOOK_APP_ID=your-facebook-app-id
      - FACEBOOK_APP_SECRET=your-facebook-app-secret
      - REACT_APP_API_URL=http://localhost:5173

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
