# Use Node.js LTS version for the client
FROM node:20

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json for dependency installation
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the client code
COPY . .

# Build the client app
RUN npm run build

# Expose the port that React uses
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
