# Use Node.js LTS version for the backend
FROM node:20

# Set the working directory
WORKDIR /app

# Copy dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the server code
COPY . .

# Expose the API port
EXPOSE 5001

# Start the server
CMD ["npm", "start"]
